# Header
menu:
  Articles: /
  Workout Log: /log

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- mailchimp
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /source/css/images/favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
